### ISSUE TITLE
Copy task fails for tables with `json` columns

### ISSUE THREAD

**Issue by tonbadal** [173TECH/sayn#198]
I'm running a copy task with a table `users` that contains a `metadata` column with type `json`.
 
```yaml
tasks:
  copy_users:  
    type: copy
    source:
      db: input_db
      table: users
    destination:
      db: output_db
      table: users
```

And when running the pipeline I get the following error:
```
9f2c0441-f1ac-430b-9d88-8223ee5ec428|2022-07-30 17:27:40,354|INFO|Run Steps: Prepare Load, Load Data, Move Table
9f2c0441-f1ac-430b-9d88-8223ee5ec428|2022-07-30 17:27:40,355|INFO|[1/3]  Executing Prepare Load
9f2c0441-f1ac-430b-9d88-8223ee5ec428|2022-07-30 17:27:40,453|INFO|[1/3]  Prepare Load (97.8ms)
9f2c0441-f1ac-430b-9d88-8223ee5ec428|2022-07-30 17:27:40,453|INFO|[2/3]  Executing Load Data
9f2c0441-f1ac-430b-9d88-8223ee5ec428|2022-07-30 17:27:41,384|ERROR|Failed (2s) invalid input syntax for type json
DETAIL:  Token "'" is invalid.
CONTEXT:  JSON data, line 1: {'...
COPY sayn_tmp_users, line 10, column metadata: "{'title': 'Engineer'}"
```

I've successfully copied other tables that don't have `json` columns.

Both input and output databases are PostgreSQL, runnning in Python 3.9.13, SAYN version `0.6.5`.
